# Copiado a partir de: https://metrics.lecoq.io
name: Metrics
on:
  # Executa Todo dia as 00:00 ---> https://crontab.guru/every-day
  schedule: [{cron: "0 0 * * *"}]
  # É executado ao relizar um Push para "main"\"master ou Manualmente
  workflow_dispatch:
  push: {branches: ["master", "main"]}

# Executa os Trabalhos
jobs:
  github-metrics:
    # Define o Sistema Operacional que será executado
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Meu GitHub Token (Usado para a geração)
          token: ${{ secrets.METRICS_TOKEN }}

          # Configurando o .SVG 
          user: guilhermepalma
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
